---
- name: Check if Boto is installed
  command: bash -c "pip list | grep 'boto '"
  register: boto_installed
  ignore_errors: True
  tags:
    - boto

- name: Install Boto if its uninstalled
  pip: name=boto state=latest
  when: boto_installed|failed
  tags:
    - boto

- name: Check if AWS CLI is installed
  command: bash -c "aws --version 2>&1 | grep aws-cli*"
  register: aws_cli_installed
  ignore_errors: True
  tags:
    - awscli

- name: Install AWS CLI if its uninstalled
  pip: name=awscli state=latest
  when: aws_cli_installed|failed
  tags:
    - awscli

- name: Create .aws directory under user home for AWS CLI config 
  file:  
    path: "{{ ansible_env.HOME }}/.aws"
    state: directory
    owner: "{{ ansible_user }}"
    mode: 0755
  when: aws_cli_installed|failed
  tags:
    - awscli

- name: Copy AWS CLI config and credentials to machine using templates
  template:  
    src: "roles/setup/templates/{{ item }}.j2"
    dest: "{{ ansible_env.HOME }}/.aws/{{ item }}"
    owner: "{{ ansible_user }}"
    mode: 0644
  with_items:
    - config
    - credentials
  when: aws_cli_installed|failed
  tags:
    - awscli

